### ISSUE TITLE
Maj Doc Bowie

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/Umbrella#112]
cf https://github.com/InseeFr/Bowie/tree/pages pour mettre à jour la documentation Bowie

- [ ] ~~Expliquer comment faire proprement un saut de ligne~~
- [ ] ~~Expliquer comment récupérer les variables d'une boucle et en faire la somme (exemple)~~
- [ ] Montrer comment faire un tableau à partir d'une formule. Wait for
   - InseeFr/Pogues/issues/762
- [ ] P-E : ajouter cas où l'on veut recharger le questionnaire, car il a été modifié
- [ ] #117
- [ ] Faire le deuxième cas d'explication de la boucle [ici ](https://inseefr.github.io/Bowie/pogues/D%C3%A9couverte%20%28le%20tutoriel%29/25-mise-en-place-boucle/) + Ajouter Info de la diff d'affichage entre boucle lié (page par page) et boucle classique (toutes les ité sur la même page)
- [ ] #116
- [x] Ajouter avertissement boucle/filtre fin de séquence pas supporter par Pogues. Ajouter une séquence à la fin pour palier le problème (uniquement pour le Web, car question générique de commentaire pour le questionnaire enquêteur)
- [ ] Ajouter dans SAV explication pour les boucles (cf issue chloé)
- [x] ajouter cas des balises Markdown non fermé (ex avec le `*`) Prendre l'issue suivant comme inspiration
    - InseeFr/Pogues/issues/859
- [ ] Ajouter une page explicative sur TrevJS
- [ ] Ajouter dans SAV comment débug les duplicatas
- [x] Ajouter pour PE info sur comment save depuis calc un fichier de var externe qui garde les `"` (cf https://help.libreoffice.org/latest/fr/text/scalc/guide/csv_files.html)
- [x] Ajouter info ici https://inseefr.github.io/Bowie/pogues/Le%20guide/Variables/nommage/ qu'on ne doit pas mettre de var externe finissant par un numéro quand c'est un vecteur car après ca peut poser problème avec l'injection de var dans PE
- [x] Remonter la gestion de nullité pour qu'elle soit plus visible
- [ ] Somme de null dans un tableau cf 
  - InseeFr/Lunatic/issues/1159
- [x] #118
- [x] #119
